require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # ItemGroup. As you add validations to ItemGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {key: 'item_groups_controller_test'+BSON::ObjectId.new.to_s}
  end

  describe "GET index" do
    it "assigns all questions as @questions" do
      puts valid_attributes
      puts valid_attributes
      question = ItemGroup.create! valid_attributes
      get :index
      assigns(:item_groups).should eq([question])
    end
  end

  describe "GET show" do
    it "assigns the requested question as @question" do
      question = ItemGroup.create! valid_attributes
      get :show, :id => question.id.to_s
      assigns(:item_group).should eq(question)
    end
  end

  describe "GET new" do
    it "assigns a new question as @question" do
      get :new
      assigns(:item_group).should be_a_new(ItemGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested question as @question" do
      question = ItemGroup.create! valid_attributes
      get :edit, :id => question.id.to_s
      assigns(:item_group).should eq(question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemGroup" do
        expect {
          post :create, :item_group => valid_attributes
        }.to change(ItemGroup, :count).by(1)
      end

      it "assigns a newly created question as @question" do
        post :create, :item_group => valid_attributes
        assigns(:item_group).should be_a(ItemGroup)
        assigns(:item_group).should be_persisted
      end

      it "redirects to the created question" do
        post :create, :item_group => valid_attributes
        response.should redirect_to(ItemGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question as @question" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemGroup.any_instance.stub(:save).and_return(false)
        post :create, :item_group => {}
        assigns(:item_group).should be_a_new(ItemGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemGroup.any_instance.stub(:save).and_return(false)
        post :create, :item_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question" do
        question = ItemGroup.create! valid_attributes
        # Assuming there are no other questions in the database, this
        # specifies that the ItemGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => question.id, :item_group => {'these' => 'params'}
      end

      it "assigns the requested question as @question" do
        question = ItemGroup.create! valid_attributes
        put :update, :id => question.id, :item_group => valid_attributes
        assigns(:item_group).should eq(question)
      end

      it "redirects to the question" do
        question = ItemGroup.create! valid_attributes
        put :update, :id => question.id, :item_group => valid_attributes
        response.should redirect_to(question)
      end
    end

    describe "with invalid params" do
      it "assigns the question as @question" do
        question = ItemGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => question.id.to_s, :item_group => {}
        assigns(:item_group).should eq(question)
      end

      it "re-renders the 'edit' template" do
        question = ItemGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => question.id.to_s, :item_group => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question" do
      question = ItemGroup.create! valid_attributes
      expect {
        delete :destroy, :id => question.id.to_s
      }.to change(ItemGroup, :count).by(-1)
    end

    it "redirects to the questions list" do
      question = ItemGroup.create! valid_attributes
      delete :destroy, :id => question.id.to_s
      response.should redirect_to(questions_url)
    end
  end

end
